#!/usr/bin/env bash
# Render the Homebrew formula for a tagged mosskeys-cli release.
#
# The formula installs the PREBUILT, SIGNED release tarball (not a from-source
# build), so `brew install` gets the exact artifact that ships with an SBOM,
# SHA-512 checksums, a cosign signature, and SLSA provenance.
#
# Usage:
#   render-homebrew-formula.sh <version> <dist-dir> > mosskeys-cli.rb
#
#   <version>   release version WITHOUT the leading v (e.g. 0.2.3)
#   <dist-dir>  directory containing the release tarballs
#               (mosskeys-<version>-<target>.tar.gz)
#
# The four platform tarballs must be present in <dist-dir>:
#   aarch64-apple-darwin, x86_64-apple-darwin,
#   aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu
#
# Homebrew requires SHA-256; the release pipeline standardizes on SHA-512 for
# SHA512SUMS, so we compute SHA-256 here directly from the tarball bytes.
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: $0 <version> <dist-dir>" >&2
  exit 2
fi

version="$1"
dist="$2"
repo="moss-piglet/mosskeys-cli"
base="https://github.com/${repo}/releases/download/v${version}"

sha256_for() {
  # $1 = target triple
  local target="$1"
  local file="${dist}/mosskeys-${version}-${target}.tar.gz"
  if [ ! -f "${file}" ]; then
    echo "::error::missing release tarball ${file}" >&2
    exit 1
  fi
  # sha256sum (Linux) or shasum -a 256 (macOS) — CI runs on ubuntu-latest.
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${file}" | awk '{print $1}'
  else
    shasum -a 256 "${file}" | awk '{print $1}'
  fi
}

url_for() {
  echo "${base}/mosskeys-${version}-$1.tar.gz"
}

mac_arm_sha="$(sha256_for aarch64-apple-darwin)"
mac_intel_sha="$(sha256_for x86_64-apple-darwin)"
linux_arm_sha="$(sha256_for aarch64-unknown-linux-gnu)"
linux_intel_sha="$(sha256_for x86_64-unknown-linux-gnu)"

cat <<EOF
# typed: false
# frozen_string_literal: true

# Homebrew formula for the mosskeys CLI.
#
# The install / package name is \`mosskeys-cli\`; the command it installs is
# \`mosskeys\`. This formula installs the prebuilt, signed binary attached to the
# GitHub Release (not a from-source build), so it shares the exact artifact that
# ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign signature, and
# SLSA build provenance. See RELEASING.md in ${repo}.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo (moss-piglet/homebrew-mosskeys-cli).
# Do not hand-edit checksums here.
class MosskeysCli < Formula
  desc "CLI and daemon for the mosskeys post-quantum key-transparency directory"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "$(url_for aarch64-apple-darwin)"
      sha256 "${mac_arm_sha}"
    end
    on_intel do
      url "$(url_for x86_64-apple-darwin)"
      sha256 "${mac_intel_sha}"
    end
  end

  on_linux do
    on_arm do
      url "$(url_for aarch64-unknown-linux-gnu)"
      sha256 "${linux_arm_sha}"
    end
    on_intel do
      url "$(url_for x86_64-unknown-linux-gnu)"
      sha256 "${linux_intel_sha}"
    end
  end

  def install
    bin.install "mosskeys"
  end

  test do
    assert_match "mosskeys #{version}", shell_output("#{bin}/mosskeys --version")
  end
end
EOF
