# typed: false
# frozen_string_literal: true

# Homebrew formula for the mosskeys CLI.
#
# The install / package name is `mosskeys-cli`; the command it installs is
# `mosskeys`. This formula installs the prebuilt, signed binary attached to the
# GitHub Release (not a from-source build), so it shares the exact artifact that
# ships with a CycloneDX SBOM, SHA-512 checksums, a keyless cosign signature, and
# SLSA build provenance. See RELEASING.md in moss-piglet/mosskeys-cli.
#
# This file is generated by .github/scripts/render-homebrew-formula.sh on each
# tagged release and committed to the tap repo (moss-piglet/homebrew-mosskeys-cli).
# Do not hand-edit checksums here.
class MosskeysCli < Formula
  desc "CLI and daemon for the mosskeys post-quantum key-transparency directory"
  homepage "https://mosskeys.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.2.3/mosskeys-0.2.3-aarch64-apple-darwin.tar.gz"
      sha256 "ec8e286896240777fb1a662d6904d7ccc4a11ed27c9cfd53b66595fbc4196aed"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.2.3/mosskeys-0.2.3-x86_64-apple-darwin.tar.gz"
      sha256 "e2d8eb9847f59e21510de07cdf0082fa99bff837fab178b52ac3e0d212e5f8ba"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.2.3/mosskeys-0.2.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9146d5c30dcf04718f1bcd44826b525ed46fea5ca6f9b1dcc3a9a712dc148a15"
    end
    on_intel do
      url "https://github.com/moss-piglet/mosskeys-cli/releases/download/v0.2.3/mosskeys-0.2.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "145d4b6ad0828e9fd94cd7f406b0735ab4a9069e430deb6c2d4a7c335fa29be2"
    end
  end

  def install
    bin.install "mosskeys"
  end

  test do
    assert_match "mosskeys #{version}", shell_output("#{bin}/mosskeys --version")
  end
end
